name: Github Action Workflow STAGE

on:
  push:
    branches:
      - staging
  repository_dispatch:
    types:
      - build-stage
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-dev:
    uses: zionweb/P3-GithubActions/.github/workflows/deploy-to-s3.yml@staging
    with:
      CI_ENV: staging
      CONTENTFUL_ENVIRONMENT: 'staging'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      S3_ORIGIN_BUCKET: ${{ secrets.S3_ORIGIN_BUCKET_STG }}
